### ISSUE TITLE
dogs becomes typelevel/cats-collections

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats-collections#104]
@stew would you consider donating dogs to become a new `cats-collections` project under typelevel org? There have been interests in having more collection implementations available for the Cats ecosystem (latest https://github.com/typelevel/cats/issues/2463).  It would be amazing to have `cats-collections` start from dogs' code base. What do you think?

**Comment by stew** [comment]
done!

**Comment by kailuowang** [comment]
@stew Sorry I didn't get to properly thank you yesterday. It's really generous of you. I believe this is a first step toward expanding the project's adoption and contributions.
