### ISSUE TITLE
0.7.0 release with new name and package

### ISSUE THREAD

**Issue by larsrh** [typelevel/cats-collections#118]
Is there anything preventing us from releasing this quickly?

**Comment by kailuowang** [comment]
👍  for releasing.

**Comment by kailuowang** [comment]
Shall we propose to the cats community to make this an official external cats module afterward? That's my original intention.

**Comment by larsrh** [comment]
> official external cats module

I'm not sure what that would entail.

**Comment by kailuowang** [comment]
The official external cats module status is a just guarantee that Cats maintainers will help maintain this project as well.

**Comment by ChristopherDavenport** [comment]
Sounds good to me.

**Comment by larsrh** [comment]
Alright. Running the release now.
