### ISSUE TITLE
Clean up DietSpec

### ISSUE THREAD

**Issue by larsrh** [typelevel/cats-collections#123]
There are a lot of commented-out tests and also it prints some messages which seem to indicate that some tests should be failing.

**Comment by anicolaspp** [comment]
@larsrh I wrote the original test suit and `Diet` implementation. At some point, we tried to migrate it to the new test style (current being executed). I will look at this and make sure all original tests are being included and then remove what is no longer needed.

**Comment by larsrh** [comment]
Excellent, thank you!

**Comment by larsrh** [comment]
#150

**Comment by johnynek** [comment]
can we close @larsrh ?
