### ISSUE TITLE
Some Refactorings

### ISSUE THREAD

**Issue by anicolaspp** [typelevel/cats-collections#134]
- Remove `DList` as `Chain` supersedes it
- Rename `Enum` as folks will think it means an enumeration ala Scala 3 enums
- Rename `Set` and `Map` to `AvlSet` and `AvlMap` to avoid name collision with stdlib
- Rename `Range` to avoid name collision with stdlib
- Remove `Streaming` in favor of fs2, monix, and iteratees
- Remove the birds package as thrush and kestrel aren't really related to collections

_Originally posted by @mpilquist in https://github.com/typelevel/cats-collections/issues/105#issuecomment-422614258_

**Comment by larsrh** [comment]
Fixed (partly) by #116 and #121. Closing in favour of #122.
