### ISSUE TITLE
Publish scala.js artifacts

### ISSUE THREAD

**Issue by sumnulu** [typelevel/cats-collections#140]
Maven artifacts are missing for scala.js

**Comment by larsrh** [comment]
That's because #128 only got merged after the 0.7.0 release. (It was absent for a long time.) Do you need it for something?

**Comment by larsrh** [comment]
Will be fixed with 0.8.0. If you need it earlier, please reopen.

**Comment by sumnulu** [comment]
Thats ok, not urgent thanks. Using snapshot for now.

**Comment by ceedubs** [comment]
I've run into this too. I noticed that this issue was closed; is there an ETA for 0.8.0?

@sumnulu you mentioned that you're using a snapshot for now. Where are you getting that snapshot? I don't see any listed on the [Sonatype snapshots](https://oss.sonatype.org/content/repositories/snapshots/org/typelevel/).

**Comment by sumnulu** [comment]
@ceedubs Sorry I meant we were using our internal build, not public snapshot which does not exists.

**Comment by larsrh** [comment]
@ceedubs The only blocker is #207 which I hope to get done by next week. Everything else can be pushed to 0.8.1 or 0.9.0.

**Comment by ceedubs** [comment]
@larsrh sounds great! No rush; it's just for a hobby project. I just thought that I would check.

**Comment by ceedubs** [comment]
@larsrh great work getting #207 through! Is there anything that I can do to help with getting 0.8 published?

**Comment by larsrh** [comment]
@djspiewak just released 0.8.0. Please check if it all works out.

**Comment by ceedubs** [comment]
@larsrh @djspiewak just gave it a try and it's working great. Thank you!
