### ISSUE TITLE
Would you accept an immutable list implementation of Okasaki

### ISSUE THREAD

**Issue by johnynek** [typelevel/cats-collections#151]
see:

https://gist.github.com/johnynek/5f4f97772595e2f65092cf51d186d6f2

it's a lot of work for everyone to send a complete PR. I want to get an idea if this is interesting to the maintainers before I do.

Alternatively, anyone is free to copy all or any of my code to send an implementation.

**Comment by larsrh** [comment]
Pending some tests and a more thorough review, I'd be in favour of inclusion. I appreciate your work.

**Comment by larsrh** [comment]
Merged.

**Comment by johnynek** [comment]
Thank you!
