### ISSUE TITLE
Diets need reasonably-fast equality

### ISSUE THREAD

**Issue by larsrh** [typelevel/cats-collections#167]

**Comment by johnynek** [comment]
I think we should be able to have `Order[Diet[A]]` in fact, since `Diet[A]` is really an ordered set of discrete countable elements.

**Comment by johnynek** [comment]
maybe the way to go is add `toIterable` to Diet and then just use lexicographical order on that iterable.

I think we can make a toIterable that is reasonably fast by making an Iterator that keeps a state of iterating through the Diet.

**Comment by larsrh** [comment]
Sounds good. That's a strategy that I have used before in this library.

**Comment by johnynek** [comment]
Indeed. So, maybe an iterator of ranges in order would make your algorithm pretty doable.

**Comment by anicolaspp** [comment]
I just love people are using `Diet`. I had a great time implementing this originally.

**Comment by anicolaspp** [comment]
@larsrh what you suggested is how `Diet` is actually implemented. When adding ranges, a comparison is done in the same way you described.

**Comment by anicolaspp** [comment]
> It might also be possible to improve on performance a little. We need an iterator that also knows where the current range ends. Then, when comparing, we can skip intermediate elements. For example, when comparing `[1..10]` and `[1..11]`, we don't need to enumerate `[1..9]`, but can skip to `10` directly.

this is not right. The elements on the range are based on a function that was used to construct the range. So there is no real way to do what you suggested.

**Comment by anicolaspp** [comment]
> Indeed. So, maybe an iterator of ranges in order would make your algorithm pretty doable.

I believe that range is iterable, somehow, already.

**Comment by anicolaspp** [comment]
@larsrh this issue is easy to fix. Two DIETs are the same if they have the exact same Ranges. I will PR this.

**Comment by anicolaspp** [comment]
I added a PR on this
