### ISSUE TITLE
Make data structures covariant?

### ISSUE THREAD

**Issue by ceedubs** [typelevel/cats-collections#210]
Some (most?) of the structures in cats-collections, such as `Diet` and `Range` are covariant in nature, but not by definition. This leads to some minor awkwardness like [asInstanceOf calls](https://github.com/typelevel/cats-collections/blob/8089582ed7fc61f9c23a0bf76ac3401585e1a98e/core/src/main/scala/cats/collections/Diet.scala#L287). It also prevents 3rd party data types that contain these structures from being declared as covariant, which there isn't really a good workaround for.

I've gone back and forth on variance in Scala, but over time I've settled on the opinion that variance is useful in Scala, it isn't really problematic as long as you avoid things like universal equality, and that you shouldn't fight it. If cats-collections maintainers want to stick to invariance, that's okay but I wanted to ask about this and would be happy to do legwork in conversion if there's interest.

**Edit**: I guess that there's also perhaps a consistency argument since data structures such as `NonEmptyList` in Cats are already covariant.

**Comment by johnynek** [comment]
I personally prefer them to be covariant where possible as well.

**Comment by larsrh** [comment]
Good point. I'd be very happy to accept such a PR.

**Comment by ceedubs** [comment]
I'm going to go ahead and close this out. `Dequeue` is the only data structure currently in cats-collections that I'm convinced is improved by being made covariant, and that was done in #214. These sort of general issues can hang around forever. People can create separate issues for any individual structures that they think should be converted.
