### ISSUE TITLE
Publish artifacts for Scala.js 1

### ISSUE THREAD

**Issue by mperucca** [typelevel/cats-collections#330]
Publish Scala.js 1 artifacts for version 0.9.0 to Maven

**Comment by larsrh** [comment]
I'm surprised that those don't exist yet :thinking: I'll get right on that.

**Comment by larsrh** [comment]
Sadly I was unable to pick a commit that supports both Scala.js 0.6 and 1, so I released a fresh 0.9.1 based on master.
