### ISSUE TITLE
0.9.4 as intermediate release

### ISSUE THREAD

**Issue by gemelen** [typelevel/cats-collections#456]
Make a release of 0.9.4 version from current (or so) state.
This would cover the gap from previous release and what was done after that without significant changes for end-users.

**Comment by gemelen** [comment]
@osleonard WDYT about this?

**Comment by armanbilge** [comment]
@gemelen now seems like a really great time to do this release :)

https://typelevel.org/sbt-typelevel/faq.html#how-do-i-cut-a-release
