### ISSUE TITLE
Functional Graph?

### ISSUE THREAD

**Issue by anicolaspp** [typelevel/cats-collections#50]
Should we add functional graph manipulation? such as Dijkstra?

**Comment by anicolaspp** [comment]
do we have this on cats or a subproject? I think dogs is a good place for it seems we have all other data structures in here

**Comment by stew** [comment]
my tendency is to work on quiver instead: https://github.com/oncue/quiver for graph stuff. Runar is working on it actively and I think its a pretty solid foundation to start building on

**Comment by larsrh** [comment]
[Quiver](https://github.com/Verizon/quiver) indeed seems to solve this problem.
