### ISSUE TITLE
Adding Bounded to enhance Enum?

### ISSUE THREAD

**Issue by yilinwei** [typelevel/cats-collections#56]
I was wondering whether `Bounded` like the one in [monocle](https://github.com/julien-truffaut/Monocle/blob/4bebf15f825d593ff25287903d9b2dfe2ea972e1/core/shared/src/main/scala/monocle/internal/Bounded.scala) would be a typeclass which should belong within dogs since `Enum` exists and it would be useful to be able to call a variant of the `succ` method which returned an `Option` if at the maximum/minimum for user defined enumerated types.

It's worth noting that in `scalaz` the `Bounded` and `Enum` typeclass are one and the same which is another way of adding the bounds.

**Comment by anicolaspp** [comment]
Isn't `Bounded` similar to `dog.Range`?

**Comment by yilinwei** [comment]
@anicolaspp Looking through the docs I would argue not, since `Range` is concrete rather than on `A` itself.

Consider a bounded enumeration for the days of the week, the `Max` would be `Sunday` and the `Min` would be `Monday`, that is to say `succ(Sunday) === Sunday` and `prev(Monday) === Monday`

`Range` on the other hand seems to represent a concrete interval which is user-defined.

**Comment by anicolaspp** [comment]
@yilinwei that is basically `Range`. You only need a custom `Enum`. However, I also get your point. I can do `Bounded` based on  `Range`.

**Comment by anicolaspp** [comment]
@yilinwei I will propose an implementation of `Bounded`by the end of the week. Please, review after PR

**Comment by yilinwei** [comment]
I don't even remember why I needed this.
