### ISSUE TITLE
Create PDF documentation.

### ISSUE THREAD

**Issue by frgomes** [typelevel/cats-collections#75]
PDF documentation would be useful when there's no internet connection.

I've created some scripts which work well enough for ``cats``, ``dogs`` and ``fetch``, as shown below:
https://github.com/frgomes/debian-bin/blob/master/bash_30pdf.sh
https://github.com/frgomes/debian-bin/blob/master/bash_30httrack.sh
https://github.com/frgomes/debian-bin/blob/master/bash_31makepdf_cats.sh
https://github.com/frgomes/debian-bin/blob/master/bash_31makepdf_dogs.sh
https://github.com/frgomes/debian-bin/blob/master/bash_31makepdf_fetch.sh

I'm not suggesting you guys adopt these scripts.
However, anyone willing to do that may eventually find some pointers here.

**Comment by larsrh** [comment]
I'm closing this issue because there didn't seem to be much interest and the links don't work anymore. If you'd like to start working on it again, please feel free to reopen.

(If this somehow could be made to work together with `sbt-microsite` I'd be happy to consider this for inclusion.)
