### ISSUE TITLE
Catenable stack-ended queue

### ISSUE THREAD

**Issue by edmundnoble** [typelevel/cats-collections#76]
Any place for `fs2.util.Catenable` here aka `StackEndedQueue`? Benchmarks here show it is the fastest sequence data structure in Scala as of functional-streams-for-scala/fs2/#784 (if you don't need `unsnoc`): https://ethercalc.org/kknm1xz3mb5s_3ht2cokr07oy/app

**Comment by mijicd** [comment]
I'll try to take care of this one.

**Comment by ChristopherDavenport** [comment]
How is this different than Chain which I believe was the combination of Catenable and previous chain work?

**Comment by mijicd** [comment]
Hm, you're right, accompanied by the long discussion in [this issue](https://github.com/typelevel/cats/issues/2358) and its [closing PR](https://github.com/typelevel/cats/pull/2371).

My mistake for picking it up. Should the issue be closed then?

**Comment by larsrh** [comment]
I wasn't aware that's the same data structure. We should close this, then.
