### ISSUE TITLE
Disjoint-Set

### ISSUE THREAD

**Issue by lewismj** [typelevel/cats-collections#87]
Hi,

I re-raised a PR for a DisjointSet, I tidied up the branch, so there is a single commit for the set, with test and doc.

https://github.com/stew/dogs/pull/86
I did an 'sbt clean test tut', and it all runs fine locally.

Hopefully there is home for this within dogs, I think there are a few others that may be useful (and don't go to heavily into the work done in quiver).

--Mike

**Comment by pfcoperez** [comment]
Hi @lewismj , I was about to open the a PR with the functionality for disjoint sets when I found yours. I wanted to bring into dogs the implementation I published at 
https://github.com/pfcoperez/algorithmaday/tree/master/src/main/scala/org/pfcoperez/dailyalgorithm/datastructures/sets

Which is a pure functional version of the structure described at [CLRS](https://en.wikipedia.org/wiki/Introduction_to_Algorithms). I implemented it in Python in 2012 and [provided an small summary of the structure described by Thomas Cormen](http://orionsword.no-ip.org/blog/wordpress/?p=246) and I adapted it to a functional style. 

In fact I also provided a state monad set of operation thus making it able to be used using `for` notation in such a way that the state propagation is transparent for the user:

![Use of the sate monad](http://imgur.com/ZPxVVVp)

The point is that I was reviewing your implementation and I see its simple and nice and it also implements **union by rank heuristic**. However it seems to lack the **path compression heuristic**. That is OK for most cases but it can lead to degraded states  where lookups can be as slow as **O(n)**. Check the how the tree depth increases in this example where the path compression is not being applied:

![Disjoint sets degradation](http://imgur.com/g19X56l)

I hope you don't mind I open a PR with my version so we can discuss the differences.

**Comment by lewismj** [comment]
Looks good, I thought about implementing the path compression (I mentioned it in the code comment), but decided not to in the end. It was partly because I wanted to avoid bringing in a dependency like Cats or roll my own Monad. I wan't sure about bringing in a dependency on Cats of if dogs had to be standalone... I couldn't decide in the end if it was worth doing or not...

**Comment by pfcoperez** [comment]
Hi @lewismj , the implementation at https://github.com/pfcoperez/algorithmaday/blob/master/src/main/scala/org/pfcoperez/dailyalgorithm/datastructures/sets/DisjointSets.scala doesn't use Cats, it follows a standalone approach as you suggested, it is curious that we share the same criteria in that regards :smile: 

It has a wrapper to make it "Cats friendly": https://github.com/pfcoperez/algorithmaday/blob/master/src/main/scala/org/pfcoperez/dailyalgorithm/datastructures/sets/MonadicDisjointSets.scala

Not implementing one of the heuristics might be enough, there are some corner cases leading to the need of path compression. Nevertheless, I fear that path compression is required to keep time complexity bounds.

I've already created a PR (https://github.com/stew/dogs/pull/90) with an implementation including path compression.

Nice relatively unknown data structure, isn't it?

**Comment by anicolaspp** [comment]
This has been already merged.

**Comment by larsrh** [comment]
Thanks!
