### ISSUE TITLE
All links at https://stew.github.io/dogs/ lead to 404

### ISSUE THREAD

**Issue by martin-g** [typelevel/cats-collections#97]
Hi,

The links at https://stew.github.io/dogs/ seem to be broken.

**Comment by akilegaspi** [comment]
This seems to be fixed already

**Comment by larsrh** [comment]
The website is currently broken because the repository name changed. Closing this in favour of #105.

**Comment by larsrh** [comment]
New website is now at: https://typelevel.org/cats-collections/
